# Generated by Django 2.2.5 on 2019-11-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Pages',
        ),
    ]
