# Generated by Django 2.2.5 on 2019-12-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='link',
            field=models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
