# Generated by Django 2.2.5 on 2019-12-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191130_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='link',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
