# Generated by Django 2.2.5 on 2019-12-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_pages_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='id',
        ),
        migrations.AlterField(
            model_name='pages',
            name='link',
            field=models.CharField(default='hans', max_length=100, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
