# Generated by Django 2.2.5 on 2019-12-11 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=True, related_name='children', to='blog.BlogCategory')),
            ],
            options={
                'verbose_name_plural': 'BlogCategory',
                'ordering': ['category', 'parent__category'],
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('datePosted', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=False, to='blog.BlogCategory')),
            ],
            options={
                'ordering': ['-datePosted'],
            },
        ),
    ]
