# Generated by Django 3.0.2 on 2020-03-01 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.BlogCategory')),
            ],
            options={
                'verbose_name_plural': 'BlogCategory',
                'ordering': ['category', 'parent__category'],
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('abstract', models.TextField()),
                ('content', models.TextField()),
                ('datePosted', models.DateTimeField(default=django.utils.timezone.now)),
                ('mainImage', models.ImageField(upload_to='')),
                ('mainImageAlt', models.CharField(blank=True, max_length=2000)),
                ('subImage1', models.ImageField(blank=True, null=True, upload_to='')),
                ('subImage1Alt', models.CharField(blank=True, max_length=2000)),
                ('subImage2', models.ImageField(blank=True, null=True, upload_to='')),
                ('subImage2Alt', models.CharField(blank=True, max_length=2000)),
                ('subImage3', models.ImageField(blank=True, null=True, upload_to='')),
                ('subImage3Alt', models.CharField(blank=True, max_length=2000)),
                ('subImage4', models.ImageField(blank=True, null=True, upload_to='')),
                ('subImage4Alt', models.CharField(blank=True, max_length=2000)),
                ('subImage5', models.ImageField(blank=True, null=True, upload_to='')),
                ('subImage5Alt', models.CharField(blank=True, max_length=2000)),
                ('subImage6', models.ImageField(blank=True, null=True, upload_to='')),
                ('subImage6Alt', models.CharField(blank=True, max_length=2000)),
                ('subImage7', models.ImageField(blank=True, null=True, upload_to='')),
                ('subImage7Alt', models.CharField(blank=True, max_length=2000)),
                ('subImage8', models.ImageField(blank=True, null=True, upload_to='')),
                ('subImage8Alt', models.CharField(blank=True, max_length=2000)),
                ('subImage9', models.ImageField(blank=True, null=True, upload_to='')),
                ('subImage9Alt', models.CharField(blank=True, max_length=2000)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogCategory')),
            ],
            options={
                'ordering': ['-datePosted'],
            },
        ),
    ]
