# Generated by Django 3.0.2 on 2020-02-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='mainImageAlt',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subImage1Alt',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subImage2Alt',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subImage3Alt',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subImage4Alt',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
