# Generated by Django 2.2.5 on 2019-12-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='hanis'),
            preserve_default=False,
        ),
    ]
