# Generated by Django 2.2.5 on 2019-12-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191130_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMainCategories',
            fields=[
                ('mainCategorie', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('subCategories', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['mainCategorie'],
            },
        ),
    ]
