# Generated by Django 2.2.5 on 2019-12-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogmaincategories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogMainCategories',
            new_name='BlogMainCategorie',
        ),
    ]
