# Generated by Django 2.2.5 on 2019-12-07 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191207_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmaincategorie',
            old_name='subCategories',
            new_name='allowSubCategorie',
        ),
        migrations.CreateModel(
            name='BlogSubCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategorie', models.CharField(default='---', max_length=300)),
                ('mainCategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='blog.BlogMainCategorie')),
            ],
        ),
    ]
