# Generated by Django 2.2.5 on 2019-12-07 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20191207_1844'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPosts',
            new_name='BlogPost',
        ),
        migrations.AlterModelOptions(
            name='blogmaincategorie',
            options={'ordering': ['maincategorie']},
        ),
        migrations.AlterModelOptions(
            name='blogsubcategorie',
            options={'ordering': ['maincategorie', 'subcategorie']},
        ),
        migrations.RenameField(
            model_name='blogmaincategorie',
            old_name='allowSubCategorie',
            new_name='allowSubcategorie',
        ),
        migrations.RenameField(
            model_name='blogmaincategorie',
            old_name='mainCategorie',
            new_name='maincategorie',
        ),
        migrations.RenameField(
            model_name='blogsubcategorie',
            old_name='subCategorie',
            new_name='subcategorie',
        ),
        migrations.RemoveField(
            model_name='blogsubcategorie',
            name='mainCategorie',
        ),
        migrations.AddField(
            model_name='blogsubcategorie',
            name='maincategorie',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='blog.BlogMaincategorie'),
            preserve_default=False,
        ),
    ]
